### ISSUE TITLE
[WIDGET] Mentor preview widget

### ISSUE THREAD

**Issue by adityathakurxd** [adityathakurxd/university#11]
A widget to display all mentors who have contributed a roadmap.

![men](https://user-images.githubusercontent.com/53579386/134878333-915b039b-5467-4e7d-8350-1f336323331b.png)

**Comment by palak296** [comment]
Hello, I would like to work on it.

**Comment by adityathakurxd** [comment]
![designs](https://user-images.githubusercontent.com/53579386/135319501-3bca7df5-bf0b-41ec-9132-9900ef290f42.png)

**Comment by adityathakurxd** [comment]
Hey @palak296, Sure please go ahead.

You'll need to create a widget that can be reused in the mentors' screen that'll have details like:

- Image of mentor
- Name of mentor
- A small title
- and, if possible GitHub and LinkedIn icons that are clickable.

If you have any questions, Tag me here or on Discord (Link: https://teamaditya.co/)
