### ISSUE TITLE
[WIDGET] Mentor preview widget extended

### ISSUE THREAD

**Issue by adityathakurxd** [adityathakurxd/university#12]
![mentor](https://user-images.githubusercontent.com/53579386/134878586-4973e348-0118-40bf-a1ae-1adde3c32388.png)

**Comment by Shubham20052001** [comment]
I would like to take up this issue...!!
Can you explain it a bit more briefly...

**Comment by adityathakurxd** [comment]
Hey @Shubham20052001, Sure please go ahead.

You'll need to create a widget that can be reused in the mentors' screen that'll have details like:
- Image of mentor
- Name of mentor
- A small title
- and, GitHub and LinkedIn icons that are clickable.

The said widget is to be used on the 3rd screen as shown in the design image below.

![designs](https://user-images.githubusercontent.com/53579386/135320467-7ae74378-d8b9-4e47-a580-21a6080b40ad.png)

If you have any questions, Tag me here or on Discord (Link: https://teamaditya.co/)

**Comment by Shubham20052001** [comment]
I made the widget in the file named as mentor_widget_extended.dart . I also went ahead and made a mentor folder inside of which are the files mentor_screen.dart and mentor_widget_extended.dart . 
![Screenshot_1632985671](https://user-images.githubusercontent.com/77091152/135404161-4e3c2cf9-ef5f-4787-8464-08e3a31f1a6e.png)
This is the snap of the widget that I made. I have used some placeholders for testing.
![structure](https://user-images.githubusercontent.com/77091152/135404361-3ddf3e59-9ffd-4fe2-87b6-4525badfff34.PNG)
This is the project structure.

Let me know if everything is fine or not. So I'll go and create a PR accordingly.

**Comment by adityathakurxd** [comment]
yesssirr looks amazing! @Shubham20052001 The project structure is well thought. Great work!
There are also issues #8 and #11 being worked on. Both of them would need the `mentor_screen.dart` so I'll refractor this later.

PS. Only PRs created after Oct 1 would be counted under Hacktoberfest.

**Comment by adityathakurxd** [comment]
Only just small fixes:
- align the F of Flutter Dev with M of Mentor
- Replace icons with LinkedIn, GitHub, and Instagram

**Comment by Shubham20052001** [comment]
Hey , I have fixed the minor bugs that you pointed out
![Screenshot_1633025625](https://user-images.githubusercontent.com/77091152/135571408-f590f21c-2eb8-4ca0-9d4b-aa6b9b3de49c.png).

Also I have added the "assets" folder in the structure.

**Comment by adityathakurxd** [comment]
Awesome! @Shubham20052001 go ahead and make the PR!
