### ISSUE TITLE
[SCREEN] Pathway screen

### ISSUE THREAD

**Issue by adityathakurxd** [adityathakurxd/university#13]
The screen would display the roadmap to learning a tech stack.
The screen should have:

- either text (heading and subtext) with clickable tiles
- or, could be a video or link embed.

## Design
![designs](https://user-images.githubusercontent.com/53579386/134879074-14427a4c-9d18-43f6-a033-70d9dbdf997d.png)

Refer `pathway` screen (2nd from right).

**Comment by ShrutiJ-01** [comment]
Hey @adityathakurxd ! I'd like to work on this issue

**Comment by adityathakurxd** [comment]
Hey Shruti, Sure please go ahead. 🌟

You'll need to create a Pathway Screen that can be used to display the roadmaps.
These roadmaps would have links to YouTube videos, articles, or documentation links.

**Please feel free to design as per your choice.**
It could be clickable tiles that redirect to a URL using the launcher package.
Or, if possible you can try embedding links in the app.

Here is a reference video for timeline-like design in Flutter: https://youtu.be/2jPAUqvRelM

If you have any questions, Tag me here or on Discord (Link: https://teamaditya.co/)

**Comment by adityathakurxd** [comment]
Hi @ShrutiJ-01, The repository did not have the firebase `.json` initially.
I have added it in the latest merge #15 

Please make sure you:
- Go to your fork on GitHub
- Click on Fetch upstream
![adityathakurxd_Hacktoberfest2021_ Curated list of beginner-friendly issues for Hacktoberfest 2021 _ Raise PR to add your issues - Google Chrome 9_29_2021 3_01_15 PM (2)](https://user-images.githubusercontent.com/53579386/135288819-edc33fee-f2ae-411a-b895-7d6145e7cba1.png)
- and, then 'Fetch and merge'

It should Fetch and merge upstream commits from my main to your fork.

Happy contributing 🎉 Let me know if you have any issues!

**Comment by ShrutiJ-01** [comment]
Hey @adityathakurxd , I have made a UI Accord to the Video you referenced and on clicking each tile URL launcher opens up the associated link in a browser

However, I've found a package that allows playing videos inline

https://pub.dev/packages/youtube_player_flutter

Is this similar to what you visualized when you said the timeline cards could have video embeds?

**Comment by adityathakurxd** [comment]
Hi, Yes this is one of the liked packages and I had looked it up.
But, I was thinking of **having embeds** instead of playing the video in the app.

Something like Notion, and Medium let you do.

![Socialite - Google Chrome 9_30_2021 1_12_07 PM (2)](https://user-images.githubusercontent.com/53579386/135409513-74f4d524-a2b4-4085-b296-2eb61f94ca2c.png)

Because my goal with the app is to later reach out to people in the community and ask them for roadmaps to master a skill.
I believe some of these resources would be YouTube videos and as a creator myself if we have the video playing in-app the views would be counted under external sources and would not help the YouTuber. Also, there might be some attribution issues.

So, it is best if we can have embeds which when clicked redirect to the YouTube app.
Same for GitHub repositories. 

If you can find a way to do this, that'll be really cool or you can push (whenever you're ready) the UI work you have done so far and we can take this up in a separate issue later. Maybe brainstorm on it later on the weekend and also ask the community for inputs.
