### ISSUE TITLE
Update the repo with google services .json file

### ISSUE THREAD

**Issue by srikharshashi** [adityathakurxd/university#14]
Google Services  .json file is an integral part of firebase which is missing in the repo as we can't set up our own firebase backend instance as well because SHA codes are already linked to your account

Here is an ss of the error

@adityathakurxd 

![image](https://user-images.githubusercontent.com/37980605/135278012-cd75433c-9ea9-4668-8063-eee7ffed4855.png)

**Comment by adityathakurxd** [comment]
Hi @srikharshashi, The repository did not have the firebase `.json` initially.
I have added it in the latest merge #15 

Please make sure you:
- Go to your fork on GitHub
- Click on Fetch upstream
![adityathakurxd_Hacktoberfest2021_ Curated list of beginner-friendly issues for Hacktoberfest 2021 _ Raise PR to add your issues - Google Chrome 9_29_2021 3_01_15 PM (2)](https://user-images.githubusercontent.com/53579386/135288819-edc33fee-f2ae-411a-b895-7d6145e7cba1.png)
- and, then 'Fetch and merge'

It should Fetch and merge upstream commits from my main to your fork.

Happy contributing 🎉 Let me know if you have any issues!
