### ISSUE TITLE
Add a CODE_OF_CONDUCT

### ISSUE THREAD

**Issue by adityathakurxd** [adityathakurxd/university#2]
Add a CODE_OF_CONDUCT.md to the project.

**Comment by adityaraj079** [comment]
Well @adityathakurxd let me do this also then

**Comment by adityathakurxd** [comment]
Let's leave this issue open for someone who wants to get started with a contribution! If you work with Flutter, a contribution in code would be really great. 😍

**Comment by adityaraj079** [comment]
yups, i was also thinking the same 
I request you to open more issues on this project
I will work on flutter now

**Comment by adityathakurxd** [comment]
Yes @adityaraj079 I'll add them up with designs.

**Comment by adityaraj079** [comment]
Well @adityathakurxd also plz add me in the contributors section in README.md

**Comment by adityathakurxd** [comment]
I had used an external tool to generate the image.
Link: https://contrib.rocks/preview?repo=adityathakurxd%2Funiversity

It should've refreshed on its on but I believe it doesn't work for doc changes. Let me check this after 5.

**Comment by Shash0501** [comment]
@adityathakurxd I wanted to get started to contribute to open source so I can add a CODE_OF_CONDUCT and also would be grateful if you could open more issues in the app so that I contribute to the app itself.

**Comment by adityathakurxd** [comment]
Hey, thanks! I'll assign it to you and also add some more issues this evening to contribute to the app.
Please go ahead with this one @Shash0501.
