### ISSUE TITLE
[FIX] Sign In Screen 

### ISSUE THREAD

**Issue by adityathakurxd** [adityathakurxd/university#24]
**Note**: This is a creative task that requires some brainstorming. All creative tasks are marked with 💡.

The `sign_in_screen.dart` currently uses placeholder images.
The goal is to:
- [ ] Add `flutter_svg:` package
- [ ] Look up illustration on [undraw](https://undraw.co/illustrations) 💡
- [ ] Add relevant SVGs to use in assets
- [ ] Optimize SVG using the [SVGCleaner](https://github.com/RazrFalcon/svgcleaner)
- [ ] Update the SVGs in Swiper by changing `List<String> images`
- [ ] Update bottom text with relevant description by changing `List<String> texts` 💡
- [ ] Make the background of `sign_in_screen.dart` white.
- [ ] Make the 'Sign in with Google' button primary.

That is all. 👀

**Comment by adityathakurxd** [comment]
Hey @hrigved-dev, Let me know if you want to take this up!

**Comment by hrigved-dev** [comment]
Hey @adityathakurxd, thank you for considering me. Is there any specific design that I need to follow?

**Comment by adityathakurxd** [comment]
Nothing in particular.

### Design
This is the **main design** for reference.
![designs](https://user-images.githubusercontent.com/53579386/135634243-a4b1dbce-5d5e-422a-ae1c-5e276e7865c1.png)

**There is already existing code.**

![WhatsApp Image 2021-10-01 at 7 41 18 PM](https://user-images.githubusercontent.com/53579386/135634509-ca6d90e8-a162-4de6-a789-64b068aa78d9.jpeg)

**Comment by hrigved-dev** [comment]
Alright! Please assign me this task

**Comment by hrigved-dev** [comment]
Am I supposed to change the text as well?

**Comment by adityathakurxd** [comment]
Text of? The description under images: Yes!
But, the Button text remains the same.

**Comment by hrigved-dev** [comment]
I have completed all the tasks!

**Comment by hrigved-dev** [comment]
![image](https://user-images.githubusercontent.com/63411663/135706722-d4796809-5ffe-4135-86b6-0d564d52ee40.png)
![image](https://user-images.githubusercontent.com/63411663/135706735-58f3dde4-aa86-45c7-bb34-dbdf08f085a7.png)
![image](https://user-images.githubusercontent.com/63411663/135706748-bdb703c3-1774-4bbd-8057-551d4fbe3ea8.png)

**Comment by hrigved-dev** [comment]
Let me know if any changes are required
