### ISSUE TITLE
Add a CONTRIBUTING

### ISSUE THREAD

**Issue by adityathakurxd** [adityathakurxd/university#3]
Add a CONTRIBUTING.md to the project.

**Comment by adityaraj079** [comment]
Hey @adityathakurxd  i would like to work on this issue
As i have been a part of Girlscript Winter of contribution
So i  know how and what to write in this .md file to guide a user to contribute

**Comment by adityathakurxd** [comment]
Sure! Please go ahead.

**Comment by adityaraj079** [comment]
Plz check the PR created @adityathakurxd
