### ISSUE TITLE
Add a roadmap screen

### ISSUE THREAD

**Issue by adityathakurxd** [adityathakurxd/university#36]
This would be a bit advanced issue that involves either creating a Typeform like an interface or a tree-like add node structure to take a roadmap as input from the user/mentor.

**Comment by infiniteoverflow** [comment]
Sounds challenging! I would like to work on this issue @adityathakurxd

**Comment by adityathakurxd** [comment]
The idea is to allow anyone to create a roadmap to master a skill and add resources for it.
The initial input would be a name of roadmap like "Learn FLutter"
and, then blogs (Medium Articles), YouTube videos or GitHub repos that can be taken up.

The screen to view roadmap is ready #42 Just need screens to submit these links.
