### ISSUE TITLE
[SCREEN] Profile Screen

### ISSUE THREAD

**Issue by adityathakurxd** [adityathakurxd/university#39]
We have used Provider for state management and user data is available across screens.
Your task is to create a Profile Screen with:

- [ ] Name of User
- [ ] Profile Image
- [ ] Profile Links like Instagram, GitHub and LinkedIn

### Sample
![profile](https://user-images.githubusercontent.com/53579386/135888162-1ba16ba9-0631-4df0-b8d5-4b52c352171f.png)

The bottom section would be used to display all roadmaps shared by the user. The tab is not necessary.

**Comment by adityathakurxd** [comment]
@3kdeveloper Let me know if you'd be able to integrate with Provider as well.

**Comment by divyanshkul** [comment]
Hey! @adityathakurxd 
Is this issue still up for grabs? Would love to work on it

**Comment by adityathakurxd** [comment]
@3kdeveloper had commented in the [discussion ](https://github.com/adityathakurxd/university/discussions/32#discussioncomment-1425678_). I'll wait for 24 hours to hear from him and if he doesn't I'd love to have you work on the issue.

**Comment by adityathakurxd** [comment]
There is a #41 issue open if until then you'd like to take that up @divyanshkul. 🚀

**Comment by Power-PP** [comment]
Is this issue still open? if yes can I work on it?

**Comment by adityathakurxd** [comment]
I believe @3kdeveloper isn't available to take this up. Let me know @divyanshkul if you still would like to work on this one and I'll assign it to you!

**Comment by adityathakurxd** [comment]
Thank you @Power-PP, I'll let you know if @divyanshkul isn't available to take this up.

**Comment by divyanshkul** [comment]
Yep, I'd like to work on it @adityathakurxd

**Comment by adityathakurxd** [comment]
Hey, @divyanshkul Any updates on this?
