### ISSUE TITLE
Show default image - wherever image not provided by the user

### ISSUE THREAD

**Issue by divyanshkul** [adityathakurxd/university#40]
**Is your feature request related to a problem? Please describe.**
I think this has already been planned, the current image (when logged in anonymously) is the default blue image that NetworkImage provides. The aim is to give a better "anonymous" image if the user signs in anonymously

**Describe the solution you'd like**
I Will try to add something like [this](https://freesvg.org/anonymous-user-icon)

**Comment by divyanshkul** [comment]
Let me know if I can work on this issue!

**Comment by adityathakurxd** [comment]
Hey yes! I think this can be taken up as one in #38 
Thank you so much for the SVG icon tho. Looks really cool 💯 I'll comment there and tag you.
