### ISSUE TITLE
Support for using RouteGenerator for Navigation

### ISSUE THREAD

**Issue by infiniteoverflow** [adityathakurxd/university#49]
**Is your feature request related to a problem? Please describe.**
I was thinking of using RouteGenerator to implement navigation using Named Routes than going with the traditional `Navigator.of(context).push()`.
Apparently, the app doesn't have any Navigations per se, but it will be helpful when we add more screens to the app.

**Describe the solution you'd like**
I will be creating a new `RouteGenerator` class and based on the route name passed, the appropriate screens can be returned.
After the integration the screens can be navigated using `Navigator.of(context).pushNamed('/home');`

**Comment by adityathakurxd** [comment]
It is a valid issue @infiniteoverflow! Thank you for adding this.
I have not as such used `RouteGenerator` before except when following the course. But, named routes are good practice and should be implemented.

I was wondering if we could use Navigator 2.0 for this project.
ref: https://medium.com/flutter/learning-flutters-new-navigation-and-routing-system-7c9068155ade

I want to also ship the app for the web and it'll be deployed to `freeroadmaps.web.app`. We could have custom links for roadmaps. Such that if you're a mentor, you can simply share the link which would load on the web app.

**Comment by infiniteoverflow** [comment]
Ohh thats a nice idea. Let me read through the N2.0 Docs...I can come up with something!
