### ISSUE TITLE
[SCREEN] Onboarding screen

### ISSUE THREAD

**Issue by adityathakurxd** [adityathakurxd/university#6]
## TODO
Create an `onboarding.dart` in the screens folder.
The would have 3 graphic images, 3 descriptive texts about the app, and 2 sign-in buttons.

## Design
![Untitled-2021-09-09-1008](https://user-images.githubusercontent.com/53579386/134345964-a1d35b4c-643b-4ea3-9d14-fed29c282347.png)

## Note
Please use only the null safe package for Swiper.

**Comment by Samdid** [comment]
I would like to work on this issue

**Comment by adityathakurxd** [comment]
Hey @Samdid, Please go ahead.

You'll only need to do the frontend side of things which means:

- [ ] Swiper onboarding
- [ ] Sign in with Google button
- [ ] Sign in anonymously button

**Note:**
Make sure the swiper package you use is null safe.
For the images or icons, feel free to use any as per your discretion. Make sure they are open for use.
For now, set the `onPressed` of the buttons to the empty HomeScreen widget.

If you have any questions, feel free to tag me here or on Discord (Link: [https://teamaditya.co/](https://teamaditya.co/))

**Comment by Samdid** [comment]
Okay sir! Is this repo came under Hactoberfest'21

**Comment by adityathakurxd** [comment]
Yes! I had added the Hacktoberfest topic to the repo and followed the steps listed on their website.

**Comment by Samdid** [comment]
Okay then my contribution is to be included in the hactoberfest'21 right?

**Comment by adityathakurxd** [comment]
Hey if you're only doing it for a Free T-shirt I'd recommend you to not do it. 

The repository is made for community contribution for people looking to start with Open Source. The issue had been labelled `lvl1` and not marked with Hacktoberfest label until October.

**Comment by Samdid** [comment]
Yeah exactly, I am also asking about the same. If the month of October has not started then the contribution phase may not have started so I had to confirm so I asked. And the main thing to say is, I don't think that the Hactoberfest is all about just a T-shirt. It's a mega event for open source contributors. And I heard a lot about this so I was excited to contribute in this. But I didn't know some people like you contributed here for just a T-shirt. Let it be, I am a contributor here and I'll do my work. And you are the maintainer of this repo who forget to add the label of hactoberfest and all this occurs. And I don't think, just clearing my doubt take you to unassigning the issue.

**Comment by adityathakurxd** [comment]
Alright if you still stand by the `I am a contributor here and I'll do my work`, why don't you go ahead and contribute instead of pestering over if your `contribution is to be included in the hactoberfest'21` or not :)

**Comment by adityathakurxd** [comment]
Here, added back the assign! Whenever you're ready. 🙌 Let me know if you need any help.

**Comment by Samdid** [comment]
Yeah sure👍

**Comment by Samdid** [comment]
Hey @adityathakurxd , I tried so much to find google-services.json file but didn't get. I think, it is not there in the repo. Can you please add that file? Or if it is there then please give me it's location. Because I can't run this project without that file.

**Comment by adityathakurxd** [comment]
I had added the json to gitignore. I was thinking of not having it public.
So, I removed Firebase initialization from main in latest commit. Is it still causing error?

**Comment by adityathakurxd** [comment]
While the UI changes are being done, it should not have Firebase added.
Let me try running it without and get back to you! Sorry for the inconvenience.

**Comment by Samdid** [comment]
Yeah, it's okay!

**Comment by adityathakurxd** [comment]
I tried running it without the JSON and it is working fine.
What you can do is:

- Go to your fork on GitHub
- Click on Fetch upstream
![adityathakurxd_Hacktoberfest2021_ Curated list of beginner-friendly issues for Hacktoberfest 2021 _ Raise PR to add your issues - Google Chrome 9_29_2021 3_01_15 PM (2)](https://user-images.githubusercontent.com/53579386/135242728-62192c3f-f684-489e-b223-a443b759d86e.png)

- and, then 'Fetch and merge'
 It should Fetch and merge upstream commits from my main to your fork.

or,
you can **replace the** `main.dart` code with this:

```dart
import 'package:flutter/material.dart';
import 'package:university/screens/auth/sign_in_screen.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: SignInScreen(),
    );
  }
}
```
It removes the firebase initialization and fixes the issue!

**Comment by adityathakurxd** [comment]
Also, let me know if it is running without on your system. I'll add it then if it doesn't.

**Comment by adityathakurxd** [comment]
Hey @Samdid, I have added the .json to the repository in the latest merge #15

**Comment by Samdid** [comment]
I followed all these steps, but still getting errors

**Comment by Samdid** [comment]
Oh okay, I'll check

**Comment by Samdid** [comment]
Hey @adityathakurxd, it's working
