### ISSUE TITLE
Add a bottom navigation

### ISSUE THREAD

**Issue by adityathakurxd** [adityathakurxd/university#8]
The bottom navigation would be have a home screen and a mentors screen.
Add it to the screen folder in a new file called `bottom_navigation.dart`.

## Design
![designs](https://user-images.githubusercontent.com/53579386/134545506-43fd4510-6bc4-48cf-b9c4-6266f8e08497.png)

**Comment by Dungtran713** [comment]
Hi, I would like to work on this issue

**Comment by TheJollyNaman** [comment]
Heyy @adityathakurxd !! I would like to work on this issue.

**Comment by adityathakurxd** [comment]
Sure @TheJollyNaman, Please go ahead. 

You'll have to create a new file preferably `bottom_navigation.dart` under screens to have the code it.
Please feel free to create it as per convenience. (Although I'd recommend not using an external package)

Here's a video for reference on the new material navigation bar: https://youtu.be/2emB2VFrRnA
Let me know if you have any questions! Tag me here or on Discord. 🙌

**Comment by TheJollyNaman** [comment]
Should I use the new material navigation bar which will require me to switch to the Master branch of Flutter or continue with the current stable release? Will changing to the master branch and building the nav bar will have any effect on the rest of the repo?

**Comment by adityathakurxd** [comment]
I was unsure that it is only available in master. Please continue working in stable and build the bottom nav as per convenience.

**Comment by hrigved-dev** [comment]
Hey @adityathakurxd, I am a beginner trying to contribute to open source. Could you assign me an issue to work on?

**Comment by adityathakurxd** [comment]
Hi @hrigved-dev, This issue is currently assigned to @TheJollyNaman 
He is working on it. I'll add some issues in an hour and ping you here once that is done.

Till then you can:
- [ ] Join in on Discord (Link: https://teamaditya.co/)
- [ ] Introduce yourself in introductions channel 🙌
