### ISSUE TITLE
[WIDGET] Home page Widgets

### ISSUE THREAD

**Issue by adityathakurxd** [adityathakurxd/university#9]
The home page renders a list of Resource classes which would have:

- Name of roadmap
- author's name
- count of resources
- resource list

**Comment by adityathakurxd** [comment]
Need to create a widget that displays this.
![widgets](https://user-images.githubusercontent.com/53579386/134546088-62fbfbb0-60b1-4b03-82eb-d1832c1e288a.png)

**Comment by Neha62-lit** [comment]
I would like to work on this issue!

**Comment by adityathakurxd** [comment]
Hey Neha, Sure please go ahead.

You'll need to **create a widget that can be reused** in a ListView Builder on HomeScreen to display available resources.

Please feel free to design as per your choice or a simple container with the 
- Name of roadmap
- author's name
- count of resources
- resource list

would do as well.


If you have any questions, Tag me here or on Discord (Link: [https://teamaditya.co/](https://teamaditya.co/))

**Comment by adityathakurxd** [comment]
Hi @Neha62-lit, The repository did not have the firebase `.json` initially.
I have added it in the latest merge #15 

Please make sure you:
- Go to your fork on GitHub
- Click on Fetch upstream
![adityathakurxd_Hacktoberfest2021_ Curated list of beginner-friendly issues for Hacktoberfest 2021 _ Raise PR to add your issues - Google Chrome 9_29_2021 3_01_15 PM (2)](https://user-images.githubusercontent.com/53579386/135288819-edc33fee-f2ae-411a-b895-7d6145e7cba1.png)
- and, then 'Fetch and merge'

It should Fetch and merge upstream commits from my main to your fork.

Happy contributing 🎉 Let me know if you have any issues!
